export const Resource = {
  Food: "food",
  Fuel: "fuel",
  Ammo: "ammo",
  Tool: "tool",
  Arco: "arco",
  Biomass: "biomass",
  Carbon: "carbon",
  Diamond: "diamond",
  Hydrogen: "hydrogen",
  IronOre: "iron_ore",
  CopperOre: "copper_ore",
  Lumanite: "lumanite",
  Rochinol: "rochinol",
  Sdu: "sdu",
  EnergySubstrate: "energy_substrate",
  Electromagnet: "electromagnet",
  Framework: "framework",
  PowerSource: "power_source",
  ParticleAccelerator: "particle_accelerator",
  RadiationAbsorber: "radiation_absorber",
  SuperConductor: "super_conductor",
  StrangeEmitter: "strange_emitter",
  CrystalLattice: "crystal_lattice",
  CopperWire: "copper_wire",
  Copper: "copper",
  Electronics: "electronics",
  Graphene: "graphene",
  Hydrocarbon: "hydrocarbon",
  Iron: "iron",
  Magnet: "magnet",
  Polymer: "polymer",
  Steel: "steel",
} as const;

export type ResourceKey = keyof typeof Resource;
export type ResourceType = (typeof Resource)[keyof typeof Resource];
